server:
  port: 8080
database:
  dsn: "host=localhost user=postgres password=123456 dbname=core_api port=5432 sslmode=disable TimeZone=Asia/Ho_Chi_Minh"
jwt:
  secret: "secret"
  access_expiration: 15m
  refresh_expiration: 7